name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'sw-dash/**'

jobs:
  format:
    name: prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sw-dash
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: sw-dash/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - name: check
        id: check
        run: pnpm exec prettier --check .

      - name: comment on pr
        if: failure() && steps.check.outcome == 'failure'
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "run `pnpm pretty` please :3"
            })

  typecheck:
    name: typescript
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sw-dash
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: latest

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: sw-dash/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc --noEmit

  migrations:
    name: db schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: check
        id: check
        run: |
          if git diff origin/main --name-only | grep -q "sw-dash/prisma/schema.prisma"; then
            if ! git diff origin/main --name-only | grep -q "sw-dash/prisma/migrations/"; then
              echo "missing=true" >> $GITHUB_OUTPUT
              exit 1
            fi
          fi

      - name: comment on pr
        if: failure() && steps.check.outputs.missing == 'true'
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "You changed db schema but didn't add a migration file. Run this:\n\n```\npnpm prisma migrate dev --name <your_change_name>\n```"
            })
